FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

RUN apt-get -y update && apt-get install -y --no-install-recommends python3-pip 
RUN apt install git -y

RUN git clone https://github.com/xinntao/Real-ESRGAN.git

