AWSTemplateFormatVersion: 2010-09-09

Resources:
  RealESRGANBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: real-esrgan
      AccessControl: Private
    
  RealESRGANBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref RealESRGANBucket
      PolicyDocument:
        Statement:
          - Sid: AllowPutObjectInBucket
            Effect: Allow
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Join 
              - ''
              - - !GetAtt RealESRGANBucket.Arn
                - /*