AWSTemplateFormatVersion: 2010-09-09

Resources:
  RealESRGANRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: RealESRGANRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: AmazonS3FullAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: '*'
        - PolicyName: AmazonSageMakerFullAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'sagemaker:*'
                Resource: '*'
        - PolicyName: AmazonEC2ContainerRegistryFullAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'ecr:*'
                Resource: '*'


  RealESRGANLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: SageMakerAndCloudWatchLogsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sagemaker:*'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 's3:*'
                Resource: '*'
        - PolicyName: LambdaPassRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: '*'
        
  RealESRGANLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: realesrgan
        S3Key: lambda_function/lambda_code.zip
      Handler: lambda_deployer.lambda_handler 
      Runtime: python3.9
      Role: !GetAtt RealESRGANLambdaRole.Arn
      Timeout: 120
    DependsOn:
        - RealESRGANLambdaRole
    
  LambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref RealESRGANLambda
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SageMakerModelApprovalRule.Arn
    DependsOn:
        - RealESRGANLambda
      
  SageMakerModelApprovalRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: "SageMaker Model Package Approved Event"
      EventPattern:
        source:
          - aws.sagemaker
        detail:
          ModelPackageGroupName:
            - equals-ignore-case: RealESRGAN
          ModelApprovalStatus:
            - equals-ignore-case: Approved
      State: ENABLED
      Targets:
        - Arn: !GetAtt RealESRGANLambda.Arn
          Id: !Ref RealESRGANLambda

